# Generated by Django 5.2 on 2026-04-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
            ],
            options={
                'ordering': ['-price'],
                'indexes': [models.Index(fields=['name'], name='name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_gte_18')],
            },
        ),
    ]
